File:
  extensions:
    - MetaTagFileExtension

SiteConfig:
  extensions:
    - MetaTagsSiteConfigDE

SiteTree:
  extensions:
    - MetaTagsSTE

ContentController:
  extensions:
    - MetaTagsContentControllerEXT
